version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - echo logging to ecr
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo starting build on 'date'
      - cd ./
      - docker build -t hello-world .
      - docker tag hello-world:latest 429758582529.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
 
  post_build:
    commands:
       - echo build completed on 'date'
       - echo pushing to repo
       - docker push 429758582529.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
       
 
    
